[app]
language=en
blockBonjour=false
connectionsStandalone=false

[graphics]
useJisGraphics=false
lcdPageSwitchTimer=10

[golemio]
address=http://api.golemio.cz/v4/pid/transferboards/
addressTest=http://rabin.golemio.cz/v4/pid/transferboards/
key=put_your_key_here
keyTest=put_your_test_key_here
parameters="?aswId=511_1&vehicleRegistrationNumber=6776&routeType=3"
useTestServer=true

[deviceManagementService]
deviceName=VDV301Display
deviceManufacturer=ROPID
deviceSerialNumber=654321
deviceClass=InteriorDisplay
deviceId=77
version=2.2
port=42476

[cisSubscriber]
port=48478
version=2.3CZ1.0
;structure="CurrentDisplayContent"
structure="AllData"
;replyPath=/xxx

[window]
defaultScreen=1
fullscreen=false

